// ParityTests.swift
// Validates Swift port output equals the reference Python library's
// output byte-for-byte. Fixtures generated by scripts/generate_fixtures.py.

import XCTest
@testable import ChineseITN

struct Fixture: Decodable {
    let category: String
    let source: String
    let input: String
    let expected: String
}

final class ParityTests: XCTestCase {

    static var fixtures: [Fixture] = {
        guard let url = Bundle.module.url(forResource: "Fixtures/parity",
                                          withExtension: "json") else {
            XCTFail("Fixture file not found in test bundle")
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([Fixture].self, from: data)
        } catch {
            XCTFail("Failed to load fixtures: \(error)")
            return []
        }
    }()

    func testFixturesLoaded() {
        XCTAssertFalse(Self.fixtures.isEmpty, "No fixtures loaded")
        print("Loaded \(Self.fixtures.count) parity fixtures")
    }

    func testAllFixtures() {
        var pass = 0
        var fail: [(Fixture, String)] = []
        for fx in Self.fixtures {
            let actual = ChineseITN.normalize(fx.input)
            if actual == fx.expected {
                pass += 1
            } else {
                fail.append((fx, actual))
            }
        }
        let total = Self.fixtures.count
        print("Parity: \(pass)/\(total) (\(Double(pass) / Double(total) * 100)%)")
        if !fail.isEmpty {
            print("\nFailures:")
            for (fx, actual) in fail {
                print("  [\(fx.category)] \(fx.input.debugDescription)")
                print("    expected: \(fx.expected.debugDescription)")
                print("    actual:   \(actual.debugDescription)")
            }
        }
    }

    // Per-category tests for finer-grained diagnostics.
    func testCardinalPure() { runCategory("cardinal_pure") }
    func testCardinalInSentence() { runCategory("cardinal_in_sentence") }
    func testDecimal() { runCategory("decimal") }
    func testWhitelist() { runCategory("whitelist") }
    func testDate() { runCategory("date") }
    func testTime() { runCategory("time") }
    func testMoney() { runCategory("money") }
    func testFraction() { runCategory("fraction") }
    func testLicensePlate() { runCategory("license_plate") }
    func testTelephone() { runCategory("telephone") }
    func testElectronic() { runCategory("electronic") }
    func testMix() { runCategory("mix") }

    private func runCategory(_ name: String) {
        let cases = Self.fixtures.filter { $0.category == name }
        guard !cases.isEmpty else {
            XCTFail("No fixtures for category \(name)")
            return
        }
        var failures: [(Fixture, String)] = []
        for fx in cases {
            let actual = ChineseITN.normalize(fx.input)
            if actual != fx.expected {
                failures.append((fx, actual))
            }
        }
        if !failures.isEmpty {
            var msg = "\(failures.count)/\(cases.count) \(name) cases failing:\n"
            for (fx, actual) in failures {
                msg += "  [\(name)] \(fx.input.debugDescription)\n"
                msg += "    expected: \(fx.expected.debugDescription)\n"
                msg += "    actual:   \(actual.debugDescription)\n"
            }
            XCTFail(msg)
        }
    }
}
