// RobustnessTests.swift
// Comprehensive coverage of true-positive and false-positive cases.
// Inputs span every supported module (cardinal, decimal, date, time,
// money, measure, fraction, math, license plate, phone, special
// tilde/dash) plus deliberately-non-numeric inputs (whitelist idioms,
// plain text, ambiguous "一" contexts, "点" used as a verb, "X年" not
// as a year). Expected outputs are generated by WeTextProcessing
// reference library — see scripts/generate_robustness_fixtures.py.
//
// The point of this suite isn't strict byte-for-byte parity (that's
// what OfficialParityTests does against the 189-case WeText corpus);
// it's regression coverage with deliberately varied cases per module.
// Currently passing rate is tracked and asserted above a minimum.

import XCTest
@testable import ChineseITN

final class RobustnessTests: XCTestCase {

    /// Minimum overall pass rate. Raise as coverage grows.
    static let minimumRate: Double = 0.65

    /// Minimum per-category pass rate to assert no category is
    /// completely broken (e.g. if money module breaks, we want to
    /// catch it even if overall stays above the floor).
    static let perCategoryMin: Double = 0.40

    static var fixtures: [Fixture] = {
        guard let url = Bundle.module.url(forResource: "Fixtures/robustness",
                                          withExtension: "json") else {
            return []
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode([Fixture].self, from: data)
        } catch {
            return []
        }
    }()

    func testFixturesLoaded() {
        XCTAssertGreaterThan(Self.fixtures.count, 200,
                             "Robustness corpus should have 200+ cases")
    }

    func testOverallRate() {
        guard !Self.fixtures.isEmpty else {
            XCTFail("No robustness fixtures loaded")
            return
        }
        var pass = 0
        var byCategory: [String: (pass: Int, fail: Int)] = [:]
        var failures: [[String: String]] = []
        for fx in Self.fixtures {
            let actual = ChineseITN.normalize(fx.input, config: .weTextLibraryDefault)
            let isPass = actual == fx.target
            if isPass { pass += 1 } else {
                failures.append([
                    "category": fx.category,
                    "input": fx.input,
                    "expected": fx.target,
                    "actual": actual,
                ])
            }
            var bc = byCategory[fx.category] ?? (0, 0)
            if isPass { bc.pass += 1 } else { bc.fail += 1 }
            byCategory[fx.category] = bc
        }
        let total = Self.fixtures.count
        let rate = Double(pass) / Double(total)
        if let data = try? JSONSerialization.data(withJSONObject: failures,
                                                  options: [.prettyPrinted]) {
            try? data.write(to: URL(fileURLWithPath: "/tmp/itn_robustness_failures.json"))
        }

        let lines = byCategory
            .sorted(by: { $0.key < $1.key })
            .map { (cat, counts) in
                let total = counts.pass + counts.fail
                let pct = Double(counts.pass) / Double(total) * 100
                return "  [\(cat)] \(counts.pass)/\(total) (\(String(format: "%.0f", pct))%)"
            }
            .joined(separator: "\n")
        print("""

        Robustness pass rate: \(pass)/\(total) = \(String(format: "%.1f", rate * 100))%
        \(lines)

        """)

        XCTAssertGreaterThanOrEqual(rate, Self.minimumRate,
            "Overall robustness rate \(rate * 100)% below minimum \(Self.minimumRate * 100)%")
    }

    /// Catch a category regressing to zero (e.g. broken module).
    func testNoCategoryCompletelyBroken() {
        guard !Self.fixtures.isEmpty else { return }
        var byCategory: [String: (pass: Int, fail: Int)] = [:]
        for fx in Self.fixtures {
            let actual = ChineseITN.normalize(fx.input, config: .weTextLibraryDefault)
            var bc = byCategory[fx.category] ?? (0, 0)
            if actual == fx.target { bc.pass += 1 } else { bc.fail += 1 }
            byCategory[fx.category] = bc
        }
        for (cat, counts) in byCategory {
            let total = counts.pass + counts.fail
            let rate = Double(counts.pass) / Double(total)
            XCTAssertGreaterThanOrEqual(rate, Self.perCategoryMin,
                "Category [\(cat)] pass rate \(rate * 100)% below per-category floor \(Self.perCategoryMin * 100)%")
        }
    }

    // ─── True-positive smoke tests (one canonical case per module) ───
    //
    // These don't go through the fixture loop — they pin specific
    // outputs we already know to be correct. They catch a wholesale
    // module break before the broader fixture sweep.

    func testTPCardinalCanonical() {
        XCTAssertEqual(ChineseITN.normalize("一千二百三十四"), "1234")
        XCTAssertEqual(ChineseITN.normalize("两千五百万"), "2500万")
    }

    func testTPDecimalCanonical() {
        XCTAssertEqual(ChineseITN.normalize("三点一四"), "3.14")
        XCTAssertEqual(ChineseITN.normalize("零点五"), "0.5")
    }

    func testTPDateCanonical() {
        XCTAssertEqual(ChineseITN.normalize("二零零八年八月八日"), "2008/08/08")
        XCTAssertEqual(ChineseITN.normalize("二零二六年"), "2026年")
    }

    func testTPTimeCanonical() {
        XCTAssertEqual(ChineseITN.normalize("两点零二分"), "2:02")
        // Noon-prefix mapping is gated by enableTimeEnglishMapping;
        // disabled in `.default` so prefix stays Chinese, time converts.
        XCTAssertEqual(ChineseITN.normalize("早上一点零二"), "早上1:02")
        // Under weTextLibraryDefault the mapping fires.
        XCTAssertEqual(
            ChineseITN.normalize("早上一点零二", config: .weTextLibraryDefault),
            "1:02 a.m.")
    }

    func testTPMathCanonical() {
        XCTAssertEqual(ChineseITN.normalize("一加二"), "1+2")
        XCTAssertEqual(ChineseITN.normalize("二等于一加一"), "2=1+1")
    }

    func testTPLicensePlateCanonical() {
        XCTAssertEqual(ChineseITN.normalize("京A一二三四五"), "京A12345")
    }

    func testTPSpecialTildeCanonical() {
        XCTAssertEqual(ChineseITN.normalize("三五百"), "三五百")
        var cfg = ChineseITNConfig.default
        cfg.spokenRangeStyle = .expand
        cfg.rangeOutputStyle = .symbol
        XCTAssertEqual(ChineseITN.normalize("三五百", config: cfg), "300~500")
        XCTAssertEqual(ChineseITN.normalize("五六十", config: cfg), "50~60")
    }

    func testTPSpecialDashCanonical() {
        XCTAssertEqual(ChineseITN.normalize("十五六"), "十五六")
        XCTAssertEqual(ChineseITN.normalize("七百三四十"), "七百三四十")
        var cfg = ChineseITNConfig.default
        cfg.spokenRangeStyle = .expand
        cfg.rangeOutputStyle = .symbol
        XCTAssertEqual(ChineseITN.normalize("十五六", config: cfg), "15~16")
        XCTAssertEqual(ChineseITN.normalize("七百三四十", config: cfg), "730~740")
    }

    // ─── False-positive guards ────────────────────────────────────
    //
    // Each test confirms a non-numeric input passes through unchanged.
    // Listed by failure mode being guarded against.

    func testFPPlainTextUnchanged() {
        let cases = [
            "你好世界", "今天天气真好", "我爱中国",
            "明天再见", "希望一切顺利", "有事请联系我",
        ]
        for s in cases {
            XCTAssertEqual(ChineseITN.normalize(s), s,
                           "Plain text should pass through: \(s)")
        }
    }

    func testFPWhitelistIdiomsPreserved() {
        // Idioms from WeText's whitelist.tsv — these must never get
        // transformed even though they contain digit chars.
        let cases = [
            "三七二十一", "一帆风顺", "一举两得", "三心二意",
            "千变万化", "万紫千红", "百闻不如一见",
            "三言两语", "九牛一毛", "千言万语",
            "万事如意", "万无一失", "千方百计",
        ]
        for s in cases {
            XCTAssertEqual(ChineseITN.normalize(s), s,
                           "Whitelist idiom should be preserved: \(s)")
        }
    }

    func testFPDotNotDecimal() {
        // 点 used as verb/noun (not decimal separator).
        let cases = [
            "一点点", "有点冷", "差一点儿",
            "我的观点", "重点是这个",
        ]
        for s in cases {
            XCTAssertEqual(ChineseITN.normalize(s), s,
                           "点 in non-decimal context should be preserved: \(s)")
        }
    }

    func testFPYearWordNotDate() {
        let cases = [
            "年初", "年底", "去年", "明年",
            "童年时代", "新年快乐",
        ]
        for s in cases {
            XCTAssertEqual(ChineseITN.normalize(s), s,
                           "Word containing 年 (not a date) should be preserved: \(s)")
        }
    }

    func testFPAmbiguousOnePlusUnit() {
        // "一" + non-measure character — must not produce "1X".
        let cases = [
            "我说一句话", "他一个人", "再来一杯",
            "看一眼", "想一想", "试一试",
        ]
        for s in cases {
            XCTAssertEqual(ChineseITN.normalize(s), s,
                           "Ambiguous '一' + char context: \(s)")
        }
    }
}
