"""Generate a comprehensive robustness fixture file from WeTextProcessing.

For every input listed in INPUTS, the expected output is whatever
WeText's InverseNormalizer().normalize() produces. This guarantees
that our Swift port has the same definition of "correct" as the
reference library.

Inputs are organized into:
- tp_*  : true positives — should transform
- fp_*  : false positives — should pass through (or transform minimally
          and consistently with WeText)

Run via:
    micromamba run -n wetext python scripts/generate_robustness_fixtures.py

Output: Tests/ChineseITNTests/Fixtures/robustness.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


INPUTS: dict[str, list[str]] = {

    # ─── True positives ─────────────────────────────────────────────

    "tp_cardinal_small": [
        "零", "一", "二", "三", "四", "五", "六", "七", "八", "九",
        "十", "十一", "十二", "十五", "十九",
        "二十", "二十一", "二十五", "三十", "四十二", "五十五",
        "六十", "七十三", "八十八", "九十九",
    ],
    "tp_cardinal_hundreds": [
        "一百", "一百零一", "一百一", "一百一十一",
        "二百", "三百二十", "五百零五", "六百六十六",
        "七百三", "八百九十九", "九百",
    ],
    "tp_cardinal_thousands": [
        "一千", "一千零一", "一千零一十", "一千一", "一千二百三十四",
        "一千五百", "两千", "两千零五", "两千零一十二",
        "三千五百", "九千九百九十九",
    ],
    "tp_cardinal_wan_yi": [
        "一万", "两万", "一万一", "一万零一",
        "一万五千", "十万", "一百万", "一千万",
        "一亿", "三亿五千万", "十亿",
        "两千五百万", "一千万一千一百一十一",
    ],
    "tp_cardinal_pure_digit": [
        # Phone-like pure digit reads
        "幺幺零", "幺二三四", "一二三四五",
        "二零二六", "二零零八",
        "幺三五零幺二三四五六七",  # 11-digit phone
        "幺八五零幺七二零七幺九",  # 11-digit with military 拐
    ],

    "tp_decimal": [
        "一点二", "三点一四", "三点一四一五九二六",
        "零点五", "零点零八", "九点八",
        "二十一点五", "一百二十点五", "三百零五点零八",
        "负三点一四", "负零点五",
        "六十五点三三",
    ],

    "tp_date_full": [
        "二零零八年八月八日", "二零二六年五月四号", "二零零八年八月",
        "三月二十一日", "八月八日", "八月十六号",
        "二零二六年", "二千年", "一九九六年",
        "公元一九九六年", "公元一六三年",
    ],

    "tp_time_basic": [
        "三点半", "八点半", "下午三点", "上午十点",
        "上午八点半", "凌晨五点", "中午十二点", "晚上九点",
        "傍晚六点半", "凌晨三点半",
    ],
    "tp_time_minute_second": [
        "两点零二分", "十三点十分三十六秒",
        "上午一点零二分三十六秒", "早上一点零二",
        "早上一点零二分", "晚上一点零二分",
        "零点十分", "下午八点零五分",
        "上午十点零五分", "晚上十一点二十分",
    ],

    "tp_money_basic": [
        "一元", "十元", "五十元", "一百元",
        "一点二五元", "三十四点五二一元",
        "一千美元", "两百欧元", "五百美元", "三百英镑",
        "一点二五人民币", "一点二五美元",
        "价格是十三点五元", "价格是十三点五美元",
        "价格是十三点五澳元", "价格是十三点五港元",
    ],

    "tp_measure_basic": [
        "二十年后", "重达二十五千克", "最高气温三十八摄氏度",
        "实际面积一百二十平方米", "渲染速度十毫秒一帧",
        "百分之二", "百分之三十", "百分三十", "百分百",
        "百分之百", "百分之五十", "百分之九十九",
    ],

    "tp_measure_range": [
        "七八公斤", "五六十摩尔", "三五百公里",
        "三四万伏特", "百分之三十到四十一",
    ],

    "tp_fraction": [
        "二分之一", "三分之二", "十六分之三",
        "百分之三十", "百分之二", "百分之五十", "百分之九十九",
    ],

    "tp_math": [
        "一加二", "负一加二", "一加二加三",
        "二等于一加一", "二十一到一千零一",
        "六百三到六百四", "三乘以五等于十五",
        "比分定格在七十八比九十六",
    ],

    "tp_license_plate": [
        "京A幺二三四五", "京A一二三四五",
        "沪B九八七六五", "粤B五五五五五",
        "鄂A七L六二U", "皖C九B三四E",
    ],

    "tp_phone": [
        "幺三八幺幺幺零零零零零",
        "我的手机号是幺三八幺幺幺二二二三三",
        "幺幺零", "加一二三四幺三八幺幺幺零零零零零",
        "可以打我手机幺三五零幺二三四五六七",
        "可以拨打幺二三零六来咨询",
        "拨打幺二三零六",
    ],

    "tp_special_tilde": [
        # WeText special_tilde.tsv: spoken "X或Y" ranges with ~ joiner
        "三五百", "三五千", "三五万", "三四万",
        "五六十", "六七十", "七八十", "八九十",
        "一两百", "两三百", "三四百", "四五百",
        "一二", "三四", "七八", "八九",
    ],
    "tp_special_dash": [
        # WeText special_dash.tsv: tens-prefixed range with - joiner
        "十五六", "十七八", "十八九",
        "四十五六", "六十七八",
        "七百三四十", "八百五六十",
        "一万六七", "三万四五",
    ],

    "tp_mixed_sentence": [
        "估值涨了百分之三十", "团队从十五人扩到四十人",
        "我有五十块钱", "这一轮我们融了大概二千五百万美金",
        "共四百六十五篇,约三百一十五万字",
        "共计六点四二万人", "同比升高零点六个百分点",
        "总量的五分之一以上", "相当于头发丝的十六分之一",
        "同比增长百分之六点三", "增幅百分之零点四",
    ],

    # ─── False positives ───────────────────────────────────────────

    # These should NOT have spurious numeric transforms — outputs
    # generated by WeText and compared verbatim. Many will be
    # identity (input unchanged) because WeText also recognizes them
    # as non-numeric.
    "fp_whitelist_idioms": [
        # WeText whitelist.tsv entries — idioms / fixed phrases.
        # Expected: unchanged (whitelist suppresses transform).
        "三七二十一", "一共", "一个", "一下", "一些", "一起",
        "一会", "一路", "二维码", "慢一点", "一般", "统一",
        "星期一", "星期二", "星期三", "星期四", "星期五", "星期六",
        "一年一度", "一点一滴", "三心二意", "阳春三月",
        "七嘴八舌", "四分五裂", "七荤八素", "三纲五常",
        "三姑六婆", "四大皆空", "五体投地", "六神无主",
        "七窍生烟", "八面玲珑", "九牛一毛",
        # 十拿九稳 excluded — WeText doesn't list it in its whitelist
        # and would convert 十→10. We're conservative and DO preserve
        # it (see whitelistTerms in Tables.swift); strict parity check
        # below would fail, so it's omitted from the fixture set.
        "百闻不如一见", "百思不得其解", "千变万化", "千方百计",
        "千头万绪", "千言万语", "万紫千红", "万事如意",
        "万无一失", "一帆风顺", "一举两得", "三言两语",
    ],
    "fp_plain_text": [
        # Plain Chinese with no numeric content. Expected: identity.
        "你好世界", "今天天气真好", "我爱中国",
        "这是一个测试", "请帮我看一下",
        "明天再见", "希望一切顺利",
        "随便说说而已", "有事请联系我",
        "下次注意一下吧",
    ],
    "fp_ambiguous_one_unit": [
        # "一" + single char where the second char isn't a measure
        # unit and shouldn't trigger cardinal+unit.
        "我说一句话", "他一个人", "再来一杯",
        "看一眼", "想一想",
        "走一步看一步", "试一试",
    ],
    "fp_sentence_with_idiom": [
        # Whitelist idiom embedded in sentence — expected
        # behavior: idiom passes through, surrounding text normalized.
        "百闻不如一见一千零一夜也精彩",
        "做事不能三心二意",
        "他三言两语就说完了一件事",
        "做事要一举两得才好",
        "听他千言万语不如自己看一眼",
    ],
    "fp_dot_not_decimal": [
        # 点 used as verb or noun, not as decimal separator.
        # WeText may still transform some; we record its actual.
        "一点点", "有点冷", "差一点儿",
        "我的观点", "重点是这个",
    ],
    "fp_year_word_not_date": [
        # "X年" in non-date contexts. WeText behavior recorded.
        "年初", "年底", "去年", "明年",
        "童年时代", "新年快乐",
    ],
}


# Strict-parity: no overrides. Generated fixtures reflect exactly
# what the reference Python library outputs under default config.
OVERRIDES: dict[tuple[str, str], tuple[str, str]] = {}


def main():
    out_path = (Path(__file__).resolve().parent.parent
                / "Tests" / "ChineseITNTests" / "Fixtures" / "robustness.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    sys.path.insert(0, "/tmp/FunASR")
    from itn.chinese.inverse_normalizer import InverseNormalizer as WeText
    we = WeText(overwrite_cache=True)
    print("WeText loaded", file=sys.stderr)

    fixtures = []
    for category, inputs in INPUTS.items():
        for inp in inputs:
            try:
                exp = we.normalize(inp)
            except Exception as e:
                print(f"WeText ERROR on {category}/{inp!r}: {e}", file=sys.stderr)
                continue
            if (category, inp) in OVERRIDES:
                override_exp, source = OVERRIDES[(category, inp)]
                fixtures.append(dict(
                    category=category, source=source,
                    input=inp, expected=override_exp,
                ))
            else:
                fixtures.append(dict(
                    category=category, source="WeText",
                    input=inp, expected=exp,
                ))

    json.dump(fixtures, out_path.open("w"), ensure_ascii=False, indent=2)
    print(f"Wrote {len(fixtures)} fixtures", file=sys.stderr)

    by_cat: dict[str, int] = {}
    for f in fixtures:
        by_cat[f["category"]] = by_cat.get(f["category"], 0) + 1
    for cat in sorted(by_cat):
        print(f"  [{cat}] {by_cat[cat]} cases", file=sys.stderr)


if __name__ == "__main__":
    main()
