"""Generate parity fixtures from BOTH reference Python libraries.

Strategy:
  - WeTextProcessing is the primary truth oracle (broader coverage).
  - fun_text_processing is the truth oracle ONLY for the date module
    (because its "X年Y月Z日" output format we adopted) and electronic
    URL recognition.
  - A small number of "combined-best" overrides patch WeText's known
    bugs (e.g. bare "四点零八G" misclassified as time 4:08).

Run via micromamba env that has both libraries installed:
    micromamba run -n wetext python scripts/generate_fixtures.py

Output: Tests/ChineseITNTests/Fixtures/parity.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


# Inputs categorized. For each (category, input), the expected output
# is generated by the indicated source library. After generation,
# `OVERRIDES` patches specific cases to the desired combined-best form.

INPUTS_WETEXT = {
    "cardinal_pure": [
        # Single chars stay Chinese
        "一", "二", "九", "零", "两", "幺", "壹", "贰",
        # 10-99
        "十", "十一", "十二", "十九", "二十", "二十一", "三十五", "九十九",
        "六十", "八十八",
        # 100-999
        "一百", "一百一", "一百二十三", "一百零一", "一百零五",
        "二百", "三百", "九百九十九", "五百零三",
        # 1000-9999
        "一千", "一千零一", "一千二百三十四", "一千零五十",
        "一千一", "九千九百九十九", "三千五百",
        # 10000+
        "一万", "两万", "一万五千", "一万一", "一万五", "一万零一",
        # Special: kept 万 suffix
        "两千五百万", "三百万", "一千万",
        # Pure digit reading
        "一二三", "一二三四", "一二三四五", "二零二六", "二零零八",
    ],
    "cardinal_in_sentence": [
        "我有五十块钱",
        "团队从十五人扩到四十人",
        "估值涨了百分之三十",
        "这一轮我们融了大概二千五百万美金",
        "我大概要五十块钱",
        "再来一杯",
        "我说一句话",
        "他一个人",
        "我们走了三天",
    ],
    "decimal": [
        "三点二三", "二点五", "七点九九", "四点三三",
        "六十五点三", "二十一点五", "一百二十点五", "三百零五点零八",
        "变成四点三三G了", "原来你是四点零八个G",
        "三点二三。", "一百零一点零五",
        "零点五", "九点八",
    ],
    "time": [
        "下午三点", "下午三点四十五分", "下午三点半",
        "上午十点", "凌晨五点", "中午十二点", "晚上九点",
        "傍晚六点半", "三点半", "凌晨三点半会有雨",
        "上午十点零五分", "晚上十一点二十分",
    ],
    "money": [
        "五十块钱", "一百块钱", "三块五", "两千五百万美金",
        "我大概要五十块钱", "一千美金", "两百欧元",
        "五百美元", "三百英镑",
    ],
    "fraction": [
        "三分之二", "百分之三十", "百分之二",
        "百分之五十", "百分之九十九",
    ],
    "license_plate": [
        "京A幺二三四五", "京A一二三四五", "沪B九八七六五",
        "粤B五五五五五",
    ],
    "whitelist": [
        "百闻不如一见", "做事不能三心二意", "千变万化",
        "我去过九寨沟", "三国演义", "星期一开会",
        "他三言两语就说完了", "一举两得",
        "一帆风顺", "万紫千红",
    ],
    "telephone": [
        "幺三八幺幺幺零零零零零",
        "我的手机号是幺三八幺幺幺二二二三三",
        "幺幺零",
        "加一二三四幺三八幺幺幺零零零零零",
    ],
    "mix": [
        "估值涨了百分之三十团队从十五人扩到四十人",
        "百闻不如一见一千零一夜也精彩",
        "内存占用四点零八G但是变成四点三三G了",
        "今天来了五十人开会下午三点半结束",
    ],
    "date": [
        "二零二六年五月四号", "二零二六年", "五月四号",
        "三月二十一日", "公元一六八年", "零八年奥运会",
    ],
}

INPUTS_FUN = {
    # Electronic URL normalization comes from fun_text_processing;
    # WeText doesn't have a corresponding rule (returns input
    # unchanged). Keep fun-generated expected output for parity.
    "electronic": [
        "h t t p 冒号斜杆斜杠 w w w 点 baidu 点 com",
    ],
}

# Strict-parity: no overrides. Generated fixtures reflect exactly
# what the reference Python library outputs.
OVERRIDES: dict[tuple[str, str], tuple[str, str]] = {}


def main():
    out_path = Path(__file__).resolve().parent.parent / "Tests" / "ChineseITNTests" / "Fixtures" / "parity.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    sys.path.insert(0, "/tmp/FunASR")
    from itn.chinese.inverse_normalizer import InverseNormalizer as WeText
    from fun_text_processing.inverse_text_normalization.inverse_normalize import InverseNormalizer as FunText
    # overwrite_cache=True forces FST rebuild; otherwise the cached
    # binary from a prior run (possibly under different flags) leaks
    # in and silently changes expected outputs.
    we = WeText(overwrite_cache=True)
    fun = FunText(lang="zh")
    print("Both libraries loaded", file=sys.stderr)

    fixtures = []

    def emit(category, source_label, inp, expected):
        if (category, inp) in OVERRIDES:
            override_expected, override_label = OVERRIDES[(category, inp)]
            fixtures.append(dict(
                category=category, source=override_label,
                input=inp, expected=override_expected,
            ))
        else:
            fixtures.append(dict(
                category=category, source=source_label,
                input=inp, expected=expected,
            ))

    for category, inputs in INPUTS_WETEXT.items():
        for inp in inputs:
            try:
                exp = we.normalize(inp)
            except Exception as e:
                print(f"WeText ERROR on {category}/{inp!r}: {e}", file=sys.stderr)
                continue
            emit(category, "WeText", inp, exp)

    for category, inputs in INPUTS_FUN.items():
        for inp in inputs:
            try:
                exp = fun.normalize(inp)
            except Exception as e:
                print(f"fun ERROR on {category}/{inp!r}: {e}", file=sys.stderr)
                continue
            emit(category, "fun_text_processing", inp, exp)

    json.dump(fixtures, out_path.open("w"), ensure_ascii=False, indent=2)
    print(f"Wrote {len(fixtures)} fixtures", file=sys.stderr)

    by_cat: dict[str, int] = {}
    for f in fixtures:
        by_cat[f["category"]] = by_cat.get(f["category"], 0) + 1
    for cat in sorted(by_cat):
        print(f"  [{cat}] {by_cat[cat]} cases", file=sys.stderr)


if __name__ == "__main__":
    main()
